# NB10 CPU Test - Optimized Configuration (1 case)
# Quick validation test

paths:
  data_dir: "/home/wuxia/projects/family_management_hub/members/wife/medical_research/cardiac_function_extraction/data/ct_images/ct_images_dicom/chd"
  model_path: "./models/va_non_gated_ai_cac_model.pth"
  output_dir: "./output/cpu_performance_tests/optimized_1case"
  cache_dir: "./data/cache/cpu_test_optimized_1"
  log_dir: "./logs"

processing:
  mode: "pilot"
  pilot_limit: 1
  device: "cpu"
  batch_size: 1
  enable_resume: false
  slice_thickness_min: 4.0
  slice_thickness_max: 6.0

performance:
  gpu_memory_fraction: 0.9
  clear_cache_interval: 5
  num_workers: 2  # v1.1.3 optimization
  pin_memory: false

output:
  csv_encoding: "utf-8-sig"
  save_cache: true
  generate_report: true
  generate_plots: false
  figure_dpi: 300

logging:
  level: "INFO"
  log_to_file: true
  log_to_console: true
  max_file_size: 10
  backup_count: 3

advanced:
  verify_model_checksum: false
  model_checksum: ""
  use_mixed_precision: false
  random_seed: 42

clinical:
  risk_thresholds:
    very_low: 0
    low: 1
    moderate: 101
    high: 401
  report_zero_calcium: true
  flag_high_risk: true

localization:
  language: "zh_CN"
  report_language: "chinese"
  date_format: "%Y-%m-%d"
  time_format: "%H:%M:%S"
